version: 0.2
 phases:
 install: 
     runtime-versions:
     docker: 18
     commands: 
     - apt-get update -y
     - apt-get install -y jq
     - curl -L https://npmjs.org/install.sh | sh
     - npm -v
     - npm install -g cfn-create-or-update
 build:
     commands:
     - stackName="cicd-final"
     - sh deploy.sh
     - echo "teste" >> elb.txt
 post_build:
     commands:
     - echo "DONE!!!!"
     
 artifacts:
 files: 
     - elb.txt